---
- name: Create AP under specified tenant
  hosts: apic
  connection: local
  gather_facts: false


  tasks:
  - name: sdagfsdg
    aci_ap:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      state: "present"
      validate_certs: False
      tenant: "{{ tenant }}"
      description: 

